lib/ff/ruby/server/sdk/api/evaluator.rb
scripts/openapi.sh
test/ff/ruby/server/sdk/evaluator_integration_test.rb
test/ff/ruby/server/sdk/evaluator_tester.rb

WHAT
Evaluation checks for Pre-Req flags were incorrectly implemented in some Server SDKs, as they were checking for value instead of identifier this was uncaught previously because the test cases used boolean flags which had the same string for identifier and value.
FIX
Updates the PreReq check to check against a feature's `identifier` instead of `value`.
TEST
The test cases were updated to properly test with a flag that has identifier that isn't equal to value. The tests on this SDK were updated to use the new test cases.

[FFM-5355] changed prereq matches from value to identifier

---

CHANGELOG.md
Gemfile
ff-ruby-server-sdk.gemspec
lib/ff/ruby/server/sdk/version.rb
scripts/openapi.sh
scripts/sdk_specs.sh

WHAT:
This SDK claims compatibility with Ruby 2.6 on Rubygems, but was not able to be built on Ruby 2.6.
FIX:
Removed the unneeded `pp` dependency that prevented the gem from installing on Ruby 2.6.

[FFM-5354] Fixes compatibility with Ruby 2.6

---

lib/ff/ruby/server/sdk/api/default_cache.rb
lib/ff/ruby/server/sdk/api/polling_processor.rb
lib/ff/ruby/server/sdk/version.rb
scripts/sdk_specs.sh
test/ff/ruby/server/sdk/evaluator_integration_test.rb
test/ff/ruby/server/sdk/evaluator_test_result.rb
test/ff/ruby/server/sdk/evaluator_tester.rb
test/ff/ruby/server/sdk/sdk_test.rb

Remove the file cache as it is not required and caused bugs. Ensure the segments are stored using set_segment instead of set_flag on startup Add the latest evaluation tests
The Ruby SDK was failing to store some flags in its cache on startup, this meant the SDK would not function as expected. This only seemed to be a problem for the file cache, rather than in mem
cache.   The file cache could only handle UTF-8 data.
There was also a bug during startup where set_flag was being called in place of set_segment, which meant no group data was stored in the cache.
The evaluation tests were included to help test and verify the above fixes.

[FFM-5478]: Ruby SDK failed to cache some flags due to encoding

---

example/getting_started/getting_started.rb
lib/ff/ruby/server/sdk/api/inner_client.rb
lib/ff/ruby/server/sdk/api/metrics_processor.rb
lib/ff/ruby/server/sdk/api/polling_processor.rb
lib/ff/ruby/server/sdk/api/update_processor.rb
test/ff/ruby/server/sdk/sdk_test.rb

[FFM-6362] - Ruby FF SDK is not waiting initialization when using "wait_for_initialization" method.
Why
wait_for_initialization does not wait and returns too quickly, allowing caller to evaluate flags before they're ready
What
The update processor is taking a callback which is attempting to compare vairiables which haven't been set yet, causing the code to exit early. Separate the constructors and add new init methods so we are not comparing 'nil'
Testing
Tested getting started in RubyMine
[FFM-6362]: https://harness.atlassian.net/browse/FFM-6362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FFM-6362] - Ruby FF SDK is not waiting initialization when using "wait_for_initialization" method.

---

README.md
buildInContainer.sh
ff-ruby-server-sdk.gemspec
lib/ff/ruby/server/sdk/api/cf_client.rb
lib/ff/ruby/server/sdk/version.rb
scripts/openapi.sh
scripts/sdk_specs.sh

FFM-6701 - Ruby SDK 1.0.6 not working with Testgrid image
What
Remove all references to openapi_client-1.0.0, don't build it anymore as a gem when scripts/install.sh is called. Instead the generated API sources should be baked into the main SDK gem directly to simplify deployment.
Why
Ruby test grid image is failing to come up because it's trying to pull a conflicting gem called openapi_client-1.0.0 of an example project that has already been published elsewhere. Looks like openapi_client-1.0.0 was only ever meant to be a locally built gem.
Testing
Compiled and built Ruby test grid image to ensure it starts correctly with no errors.

FFM-6701 - Ruby SDK 1.0.6 not working with Testgrid image

---

Gemfile
README.md
buildInContainer.sh
example/getting_started/getting_started.rb
example/tls_example/tls_example.rb
ff-ruby-server-sdk.gemspec
lib/ff/ruby/server/sdk/api/cf_client.rb
lib/ff/ruby/server/sdk/api/config.rb
lib/ff/ruby/server/sdk/api/config_builder.rb
lib/ff/ruby/server/sdk/api/inner_client_updater.rb
lib/ff/ruby/server/sdk/connector/events.rb
lib/ff/ruby/server/sdk/connector/harness_connector.rb
lib/ff/ruby/server/sdk/version.rb
scripts/openapi.sh
scripts/sdk_specs.sh

FFM-7005 - TLS support custom CAs - remove sse-client
What
Add support for private/custom CA certs which can be passed in by the caller as a list of X.509s. Remove sse-client module since it prevents access to the underlying TLS APIs of restclient module
Why
Allow SDK to connect to non-SaaS hosted environments.
Testing
Manually

FFM-7005 - TLS support custom CAs - remove sse-client

---

.gitignore
Gemfile
ff-ruby-server-sdk.gemspec
lib/ff/ruby/server/sdk/api/config.rb
lib/ff/ruby/server/sdk/api/inner_client_flag_evaluate_callback.rb
lib/ff/ruby/server/sdk/api/metrics_event.rb
lib/ff/ruby/server/sdk/api/metrics_processor.rb
lib/ff/ruby/server/sdk/version.rb
scripts/sdk_specs.sh
test/ff/ruby/server/sdk/metrics_processor_test.rb

FFM-7285 - Remove Metrics queue and implement Map
What
Remove queue implementation and use a map to store metrics counts instead.
Why
Store each counter in a map for better memory performance. The current implementation adds a new row per eval. Using a queue can also fill up too quickly and cause the evaluation to block the user thread - until the metrics processor drains the queue which may be many seconds later.
Testing
Added new unit tests + manual

FFM-7285 - Remove Metrics queue and implement Map

---

lib/ff/ruby/server/sdk/api/auth_service.rb
lib/ff/ruby/server/sdk/api/client_callback.rb
lib/ff/ruby/server/sdk/api/inner_client.rb
lib/ff/ruby/server/sdk/connector/harness_connector.rb
test/ff/ruby/server/sdk/auth_service_test.rb
test/ff/ruby/server/sdk/cf_client_test.rb

FFM-7325 - Improve authentication retry logic
What
Harden the authentication retry logic to only retry on certain HTTP codes, certain error codes will be treated as transient and others not. We also want to ensure that while we are authenticating that default values will be served.
Why
We're doing a genernal review of network resiliency on auth and hardening code.
Testing
Manual + new unit tests added

FFM-7325 - Improve authentication retry logic

---

example/getting_started/getting_started.rb
lib/ff/ruby/server/sdk/api/auth_service.rb
lib/ff/ruby/server/sdk/api/evaluator.rb
lib/ff/ruby/server/sdk/api/inner_client.rb
lib/ff/ruby/server/sdk/api/metrics_processor.rb
lib/ff/ruby/server/sdk/api/polling_processor.rb
lib/ff/ruby/server/sdk/api/update_processor.rb
lib/ff/ruby/server/sdk/common/sdk_codes.rb
lib/ff/ruby/server/sdk/connector/events.rb
lib/ff/ruby/server/sdk/connector/harness_connector.rb
lib/ff/ruby/server/sdk/version.rb
scripts/sdk_specs.sh
test/ff/ruby/server/sdk/sdk_code_test.rb

FFM-7275 - Standardise Init / Auth /  Close / Polling / Streaming / M…etrics log messages and error messages
What
Adding standardised SDK error codes + pushing some logs down to debug to reduce noise
Why
Each SDK uses different log messages for its lifecycle. We want to standardise messages across SDKs with a unique code.
Testing
Manual testing + unit testing

FFM-7275 - Standardise SDK error codes

---

lib/ff/ruby/server/sdk/api/evaluator.rb

FFM-6503: Ruby SDK returns wrong evaluation when there are two equals rules in one group
What
Change loop to abort with true when first condition matches (OR) rather than expecting all condition to match (AND)
Why
Target groups clauses should be treated as logical ORs.
Testing
Tested with Ruby testgrid container and sdk_evaluation_test.go

FFM-6503: Ruby SDK returns wrong evaluation when there are two equals in one group

---

lib/ff/ruby/server/sdk/api/evaluator.rb

FFM-7870 - Ruby SDK - IN operator for rules is broken
What
Fix evaluation logic to correctly handle IN operator
Why
IN operator of Target Group Criteria incorrectly does a substring check of element 1 instead of checking all elements
Testing
The following testgrid tests are now working:
"GroupRules;Type=Bool;State=Enabled;InOneTwoThree;Should Return true for Target three"
"GroupRules;Type=Bool;State=Enabled;InONETWOTHREE;Should Return false for Target three"
"GroupRules;Type=Bool;State=Enabled;InOneTwoThree;Should Return false for Target THREE" 
"GroupRules;Type=Number;State=Enabled;InOneTwoThree;Should Return 324523 for Target three" 
"GroupRules;Type=String;State=Enabled;InOneTwoThree;Should Return theHobbit for Target three" 
"GroupRules;Type=Bool;State=Enabled;InONETWOTHREE;Should …

FFM-7870 - Ruby SDK - IN operator for rules is broken

---

lib/ff/ruby/server/sdk/api/evaluator.rb

Fix evaluation issue where a boolean is returned instead of a value. In the issue FFM-8670, the customer reported that flag was still returning the same true value, even though the flag was set and that boolean is compared against the list of IN clause values from the flag’s config, which always fails.

FFM-8670: Feature flag rule not being evaluated for a given attribute

---

lib/ff/ruby/server/sdk/api/evaluator.rb
lib/ff/ruby/server/sdk/dto/target.rb
lib/ff/ruby/server/sdk/version.rb
scripts/sdk_specs.sh

[FFM-8725] - Target attributes need to be defined as a hash instead of an array
What
Set attributes to hash instead of array when none are given
Why
The following exception is seen when rules are defined with an empty set of attributes:
evaluator.rb:148:in `get_attr_value': no implicit conversion of Symbol into Integer (TypeError)
Testing
New test added to TestEvaluations_ServerSDK see [FFM-8706]
[FFM-8725]: https://harness.atlassian.net/browse/FFM-8725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FFM-8706]: https://harness.atlassian.net/browse/FFM-8706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FFM-8725] - Target attributes need to be defined as a hash instead of an array

---

lib/ff/ruby/server/sdk/dto/target.rb
lib/ff/ruby/server/sdk/version.rb
scripts/sdk_specs.sh
test/ff/ruby/server/sdk/target_test.rb

[FFM-9036] - Convert target attributes with string keys to symbol keys
What
For any target attribute passed in with a string key convert them to a symbol key
Why
Make sure we’re internally consistent when handling keys
Testing
Manual + testgrid
[FFM-9036]: https://harness.atlassian.net/browse/FFM-9036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FFM-9036] - Convert target attributes with string keys to symbol keys

---

CHANGELOG.md
lib/ff/ruby/server/sdk/api/evaluator.rb
lib/ff/ruby/server/sdk/version.rb
scripts/sdk_specs.sh

Updates percentage rollout prefix to align with other SDKs. 
The prefix is backwards in this SDK, and Ruby, compared to our other SDKs. 
Manual - compared hash for given target with Golang SDK

FFM-9804 Fix percentage rollout prefix

---

lib/ff/ruby/server/sdk/version.rb
test/ff/ruby/server/sdk/sdk_test.rb

**What**
Relax test assertion since polling processor can’t always guarantee 10 iterations on slower processors (e.g. CI).
**Why**
The following assertion is failing because it is too precise
Ff::Ruby::Server::SdkTest#test_polling_processor [test/ff/ruby/server/sdk/sdk_test.rb:308]
**Testing**
Manual

[FFM-10418] - test_polling_processor breaks nightly builds

---

api.yaml
lib/ff/ruby/server/sdk/api/evaluator.rb
lib/ff/ruby/server/sdk/version.rb
scripts/sdk_specs.sh
test/ff/ruby/server/sdk/evaluator_test.rb
test/ff/ruby/server/sdk/local-test-cases/v2-andor-flags.json
test/ff/ruby/server/sdk/local-test-cases/v2-andor-segments.json
test/ff/ruby/server/sdk/sdk_test.rb

[FFM-11241] - Target v2: Adding support for AND/OR in clauses
**What**
Adding support for processing the new `GroupServingRule` in `Segment`. Also update API definition for OpenAPIGenerator plugin. The default behaviour now is to check for the existence of `GroupServingRule` if found then we ignore the old `Rules` section. Old `Rules` section will continue to work to aid transition if `GroupServingRule` is not yet populated. Each entry in `GroupServingRule` is ORed while each list of clauses is ANDed. The `GroupServingRule` with the highest priority used first to allow reordering on the backend.
**Why**
This give the customer more flexibility on how they configure their rules in the backend.
**Testing**
Initial unit tests for now + testgrid later
[FFM-11241]: …

[FFM-11241] - Target v2: Adding support for AND/OR in clauses

---

api.yaml
lib/ff/ruby/server/sdk/connector/harness_connector.rb
test/ff/ruby/server/sdk/metrics_processor_test.rb

**What**
Adds a new query parameter to tell the BE which rule JSON format the SDK is capable of handling locally
**Why**
Caching can be performed on the BE by keying on the URL
**Testing**
Manual + proxy

[FFM-11365] - Add new query parameter to target-segments

---

lib/ff/ruby/server/sdk/api/config.rb
lib/ff/ruby/server/sdk/api/metrics_processor.rb
lib/ff/ruby/server/sdk/common/sdk_codes.rb

- Splits evaluation and target metrics into their own caches:
- So that evaluations can be keyed on `flag + variation` and that we can track target metrics separately because we use the `global target` for evaluations 
- Implement seen targets - this was previously implemented but not working:
- ensures that the metrics service only gets sent target metrics for a target once, for the lifetime of the SDK instance
- ensures that the SDK processes truly unique targets fairly, and that old targets don't occupy the 100K limit set per 
- No longer flushes metrics if map is full, but instead logs a warning and returns. 
- Metrics accuracy:
- TestGrid metrics tests
- Manual sample app
- Non-anonymous targets appear in UI
- Anonymous targets don't appear in UI
- SeenTargets:
- Manual testing
- …

FFM-11211 Metrics enhancements

---

lib/ff/ruby/server/sdk/api/evaluator.rb
lib/ff/ruby/server/sdk/api/storage_repository.rb
lib/ff/ruby/server/sdk/version.rb
scripts/sdk_specs.sh

- Move the group `AND/OR` rules, and Flag `Rules`  outside of the critical evaluation path into the point we save them to the cache.
Avoid the cost of sorting multiple times during evaluations when it is unnecessary, which can add evaluation latency.
TestGrid - both old style and new style scenarios pass.

FFM-11657 Sort serving rules and flag rules in cache code

---

ff-ruby-server-sdk.gemspec

These dependencies are needed for development and/or at build time, but to the best of my knowledge, not to run the built gem. As such, to trim down dependencies in projects that install `ff-ruby-server-sdk`, I believe these three should be moved to dev dependencies.
Let me know if I need to update something else, this was done rather hastily.

move rake, minitest, standard to dev dependencies

---

docs/further_reading.md
lib/ff/ruby/server/sdk/api/auth_service.rb
lib/ff/ruby/server/sdk/api/cf_client.rb
lib/ff/ruby/server/sdk/api/inner_client.rb
lib/ff/ruby/server/sdk/common/sdk_codes.rb
lib/ff/ruby/server/sdk/connector/harness_connector.rb
lib/ff/ruby/server/sdk/version.rb
scripts/sdk_specs.sh

- Http code 0 is returned by the typheous client for any uncategorised http errors.  We should be able to assume most of the uncategorised attempts to connect to SaaS / Proxy are transient, and allow the SDK to retry. This PR adds `0` to the list of retryable codes.
- `-1` was being returned due to a bug in the OpenAPi generator, which meant the retryable codes were not being properly evaluated.  This returns the code if it exists, or -1 if not  
- Adds an optional `timeout_ms` parameter to `wait_for_initialized`
Used local proxy tool to
- return `0` for auth attempts. SDK retries
- return `404` for auth attempts, SDk does not retry
- supply `timeout_ms` argument and delay auth, the `wait_for_initialization` call unblocks and the SDK serves defaults

FFM-12088 Retry on HTTP status code 0

---

lib/ff/ruby/server/sdk/api/inner_client_flag_evaluate_callback.rb
lib/ff/ruby/server/sdk/api/metrics_event.rb
lib/ff/ruby/server/sdk/api/metrics_processor.rb
lib/ff/ruby/server/sdk/version.rb
scripts/sdk_specs.sh
test/ff/ruby/server/sdk/cf_client_test.rb
test/ff/ruby/server/sdk/metrics_processor_test.rb

We are seeing an edge case (see JIRA FFM-12192) where in very large project sizes the arguments passed to metrics functions can be invalid.  We are still to root cause this, so this PR checks for invalid metrics data and skips them if detected. 
New unit tests
Manual testing with valid and invalid inputs
Testgrid integration suite

FFM-12192 Add guards for invalid Metrics 

---

lib/ff/ruby/server/sdk/api/cf_client.rb
lib/ff/ruby/server/sdk/api/metrics_processor.rb
test/ff/ruby/server/sdk/sdk_test.rb

- We are seeing segment faults that are closely linked to the evaluation metrics map.  
- Customer shared logs to confirm the evaluation metrics map has stored corrupt data. 
Theory is when we clone the evaluation metrics map, the evaluation thread can and will modify the original map concurrently, resulting in data corruption.  Theory extends to the Segment fault being caused by this access too.
Also, the cf_client uses a class variable which is not thread safe, which could be causing issues.
Lock the cloning operation with a mutex
Replace the client class variable with a Singleton
- Unit tests for singleton access 
- Testgrid

FFM-12192 Use client Singleton / Lock eval & target map clone operation

---

lib/ff/ruby/server/sdk/api/cf_client.rb
lib/ff/ruby/server/sdk/api/inner_client.rb

**Changes**
Ensure only one instance of `CfClient` can ever be created, protect against multithreaded edge cases where multiple instances could be created in a short period by controlling access with a mutex. 
Use `condition.broadcast` instead of `condition.signal` to ensure initialised signal is received by all listeners on every thread.

feat: [FFM-12281]: thread safety fixes 
